version: '3.8'

services:
  backend:
    build:
      context: ./financial-tracker-api
      dockerfile: Dockerfile
    container_name: financial-tracker-api
    ports:
      - "8000:8000"
    env_file:
      - ./financial-tracker-api/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    volumes:
      - ./financial-tracker-api:/app
    restart: always

  frontend:
    build:
      context: ./financial-tracker-ui
      dockerfile: Dockerfile
    container_name: financial-tracker-ui
    ports:
      - "3000:3000"
    env_file:
      - ./financial-tracker-ui/.env
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./financial-tracker-ui:/app:cached # Monta o diretório do código-fonte
      - /app/node_modules                  # Evita conflitos de cache no node_modules
      - /app/.next                         # Inclui a build do Next.js
    restart: always


  postgres:
    image: postgres:13
    container_name: financial-tracker-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tracker"]
      interval: 5s
      retries: 5
    restart: always

  redis:
    image: redis:6
    container_name: financial-tracker-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
