# Generated by Django 5.1 on 2024-10-28 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_account_slug_accounttype_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'account_type')},
        ),
        migrations.AddField(
            model_name='accounttype',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='account_types', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finances.accounttype'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together={('user', 'name')},
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
    ]
