# Generated by Django 5.1 on 2025-02-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
